### ISSUE TITLE
Prevenir duplicidad

### ISSUE THREAD

**Issue by po5i** [po5i/verum#8]
Pensar en alguna manera para prevenir que varias personas ingresen la misma acta.

**Comment by rafariva** [comment]
Yo opino dejar que SI puedan ingresar varias personas el mismo acta, y de pronto mostrar una alerta (esta acta ya existe, pero igual fue guardada), porque supongamos que alguien se equivoca, o alguien sube la que no es. podría servirnos para "contrarestar" la información subida por dos personas
